/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-pWuupRV0KW4XSJ-M-9Onfik4BIIMN1CHy2vjdTM2gPXAUld2iZeyBvnQKykvmsu-gvX-Q7yReizc8ADghJrplUqftOb3LSYXZVQPdpMZj6R9VGZfL2fT9kik",
  "tt": "tt-1-oMz3BmF1kY6hjS6WtUw-LyFf-SNrxvHjv34bc4PToGw=",
  "version": "2020-11-20"
}

export default ebconfig;